default_platform(:android)

platform :android do
  desc "Upload APK to internal track"
  lane :playstore_upload do
    supply(
      json_key: "fastlane/google_play.json",
      aab: "android/app/build/outputs/bundle/release/app-release.aab",
      track: "internal",
      package_name: "com.assoodiq.devops"
    )
  end
end
